#cloud-config
packages:
  - ca-certificates
  - curl
  - git
runcmd:
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  - systemctl enable docker
  - mkdir -p /opt/clf-website
  - mkdir -p /root/.ssh
  - chmod 700 /root/.ssh
  - echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN+aVpdq+2R5pOW4hqkUiQIPGDBxbjIUqA/PkpjWXdlA clf-deploy" >> /root/.ssh/authorized_keys
  - chmod 600 /root/.ssh/authorized_keys
